# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b0c99afaca223fd8e1259198f655eb1c51d407608dea948451385cf702e9ece286799c214bcaecf9d9726938b3301fa24ff97da0edcd62330a3e580183cfbc1

test:
  secret_key_base: c2af3681c6b56536fa7f6d6ffe2f74df019b5796d76cc345ae9c5ac5352d51024c8701358b8d5b186f60327cc23b1025533b58b9e7bd8856ca8c2ce49911eb14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
